name: Sync Submodule

on:
  push:
    branches: [master] # 监听主分支的推送事件

jobs:
  sync-submodule:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: true # 确保检出 submodule 代码

      - name: Set up Git config
        run: |
          git config --global user.name "github - actions[bot]"
          git config --global user.email "github - actions[bot]@kvchen95.github.com"
          git config --global pull.rebase false

      - name: Pull latest submodule code (允许无关历史)
        run: |
          cd libs/note-rxjs  # 替换为你的子模块路径
          git config pull.rebase false  # 禁用 rebase
          git pull origin main --allow-unrelated-histories --force
          cd -
          git submodule sync
          git submodule update --init --recursive --force

      - name: Commit and push changes
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git add .
          if git diff-index --quiet HEAD --; then
            echo "No changes."
          else
            git commit -m "自动同步子模块 [skip ci]"
            git pull --rebase  # 避免推送冲突
            git push
          fi
