name: Sync Submodule

on:
  push:
    branches: [master] # 监听主分支的推送事件

jobs:
  sync-submodule:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: true # 确保检出 submodule 代码

      - name: Set up Git config
        run: |
          git config --global url."https://oauth2:${GITHUB_TOKEN}@github.com".insteadOf "https://github.com"  # 替换 GitHub 认证
          git config --global user.name "github - actions[bot]"
          git config --global user.email "github - actions[bot]@kvchen95.github.com"
          git config --global pull.rebase false

      - name: Commit and push changes
        run: |
          git submodule init
          git submodule update --init --recursive
          # 强制所有子模块切换到 master 分支
          git submodule foreach --recursive 'git checkout master'
          git add .
          if git diff-index --quiet HEAD --; then
            echo "No changes."
          else
            git commit -m "自动同步子模块 [skip ci]"
            git pull --rebase  # 避免推送冲突
            git push
          fi
